name: continous-integration of loan API

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: giving access to the repo
      uses: actions/checkout@v4
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pytest




        